parameters:
    database_driver:   pdo_mysql
    database_host:     becomeaggsch.mysql.db
    database_port:     ~
    database_name:     becomeaggsch
    database_user:     becomeaggsch
    database_password: 8v3GawM8KA
    mailer_transport:  smtp
    mailer_auth_mode:  login
    mailer_host:       SSL0.OVH.NET
    mailer_port:       587
    mailer_user:       contact@papilo.fr
    mailer_password:   contactpapilo
    locale:            fr
    secret:            6bf38d82b8fca3c2b361d5f064a7bc9155fdd37f
    debug_toolbar:          true
    debug_redirects:        false
    use_assetic_controller: true
