security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_SONATA_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                check_path: fos_user_security_check
                login_path: /
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                failure_path: /
                default_target_path: /profile
            logout:       true
            anonymous:    true
        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/improve, role: ROLE_ELEVE }
        - { path: ^/my_history, role: ROLE_ELEVE }
        - { path: ^/add_theme, role: ROLE_ELEVE }
        - { path: ^/admin/, role: ROLE_ADMIN }