<?php

namespace Main\ExerciceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciceStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceStatsRepository extends EntityRepository
{
	public function updateStats($exercice, $success)
	{
		$entity = $this->getEntityManager()->getRepository('MainExerciceBundle:ExerciceStats')->findOneBy(array("exercice" => $exercice->getId()));
		if ($entity == NULL)
		{
			$new_entity = new ExerciceStats();
			$new_entity->setExercice($exercice);
			$new_entity->setNbrePassages(1);
			if ($success === true)
				$new_entity->setTauxReussite(100);
			else
				$new_entity->setTauxReussite(0);
			$this->getEntityManager()->persist($new_entity);
		}
		else
		{
			if ($success === true)
				$entity->setTauxReussite(100*($entity->getTauxReussite()/100*$entity->getNbrePassages()+1)/($entity->getNbrePassages()+1));
			else
				$entity->setTauxReussite($entity->getTauxReussite()*$entity->getNbrePassages()/($entity->getNbrePassages()+1));
			$entity->setNbrePassages($entity->getNbrePassages()+1);
			$this->getEntityManager()->persist($entity);
		}
		$this->getEntityManager()->flush();
	}
}
