<?php

namespace Main\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseUserRepository extends EntityRepository
{

}
