<?php

namespace Main\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamenUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenUserRepository extends EntityRepository
{
}
