<?php

namespace Main\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SavoirUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavoirUserRepository extends EntityRepository
{
}
