<?php

namespace Main\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeUserRepository extends EntityRepository
{
	public function setAvailable($themes,$user)
	{
		$themes_user = $this->getEntityManager()->createQuery('SELECT IDENTITY(t.theme) as theme FROM MainUserBundle:ThemeUser t WHERE t.user ='.$user->getId())->getArrayResult();
		foreach($themes as $key => $theme)
			foreach($themes_user as $theme_user)
				if ($theme['id'] == $theme_user['theme'])
					$themes[$key]['available'] = true; 
		return $themes;

	}

}
